apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app.kubernetes.io/managed-by: terraform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
